apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sut-mg-cart-app
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  # Add labels to your application object.
  labels:
    name: mg-cart
spec:
  # The project the application belongs to.
  project: default

  source:
    source:
    path: charts
    repoURL: git@github.com:Poonnachit/mg-nod-prod-manifest.git
    targetRevision: HEAD
    helm:
      releaseName: sut-mg-cart
      valueFiles:
        - ../sut/pedjeab/mg-cart/values.yml
  
  destination:
    # cluster API URL
    server: https://kubernetes.default.svc
    # or cluster name
    # name: in-cluster
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: sut

  syncPolicy:
    automated:
      prune: true 
      selfHeal: true